language: haskell
sudo: false
ghc:
  - 7.8 # Current Haskell Platform
install:
  # TODO: Replace with version on Hackage once ParseTS has an alpha out
  - git clone https://github.com/BlocklandGlass/ParseTS.git parsets && cd parsets && cabal install --jobs && cd ..
script:
  - parsets .
